### ISSUE TITLE
Module not importing all lines

### ISSUE THREAD

**Issue by steentje34** [vanderbilt-redcap/big-data-import#1]
https://github.com/vanderbilt-redcap/big-data-import/blob/8d57f8abb3189eca7c26eb0937550dc33e2c82b0/BigDataImportExternalModule.php#L240-L246
It seems that the calculations in the referenced lines cause the module to import not all lines in a CSV. In my test case:
$fieldNamesTotal = 1236
count($content)-1 = 5107
$numberOfDataPoints = 6312252
$numberOfBatches = 6.312252
$batchSize = 809
$chunks = 6

The code then performs 809 imports with 6 lines per import, resulting in the first 4854 lines being imported. Ultimately, this causes 5107 - 4854 = 253 lines not to be imported, due to rounding. As a solution, you might swap the $chunks & $batchSize calculations and calculate them as follows:
```
$chunks = ceil($numberOfBatches);
$batchSize = ceil((count($content)-1) / $chunks);
```

In my test case, this would result in 730 imports with 7 lines per import, resulting in the first 5110 lines being imported.

For my information, what exactly is the difference between the variables $numberOfBatches, $batchSize & $chunks? As $chunks = round($numberOfBatches), the variable naming seems quite confusing.

**Comment by knil-maloon** [comment]
@steentje34 a chunck is just another part, another division, of a batch.
Have you tried to import this with a real case scenario and it wasn't importing all the data? I've tried with very big files but we never got any lines missing but I can see with your calculations getting some info missing.
The only issue I see is that if the process reads more lines and those have blank values it will give an error when trying to save them, as there won't be for example a record_id for line 5108-5110. That means adding some more logic to check that.

**Comment by steentje34** [comment]
@knil-maloon The test I performed was a real case scenario, not importing 253 lines (out of 5107).

I tested rewriting lines 240-246 in BigDataImportExternalModule.php, and this did the trick, without giving any errors:
```
$numberOfDataPoints = $fieldNamesTotal * (count($content)-1);
$numberOfBatches = $numberOfDataPoints / 1000000;
if(round($numberOfBatches) <= 0){
    $numberOfBatches = 1;
}
$chunks = ceil($numberOfBatches);
$batchSize = ceil((count($content)-1) / $chunks);
```

Finally, I simulated the calculations as programmed in the original code to assess how big of an issue this is. In the simulation, the number of fields ranged from 1 to 1000 and the number of lines from 1 to 5000. Out of the 5000000 scenarios simulated, 1394051 result in at least 1 line not being imported. The worst scenarios resulted in 597 lines not being imported.

Could you have a look at this issue?

**Comment by knil-maloon** [comment]
We are working on this and have to do some tests to ensure nothing happens but next week the new version should be available in the repository. Thanks for the checking this out.
