### ISSUE TITLE
big data import disabled all my external modules

### ISSUE THREAD

**Issue by Dave2048** [vanderbilt-redcap/big-data-import#3]
(this is report at redcap community as well, so please ignore if it's already addressed there)

i tried the big data import module. At first, everything looks fine, i enabled the module in control center then in the project. Setup alert email. Then everything went wrong once i tried to import a small csv file. i tried on two different servers, and both got the same error. Version: 9.1.2.

The file was uploaded successfully with confirmation message. After i click submit (or something like that), things start to go wrong:

1. The "delete" or "cancel current import" stop working;

2. the import page doesn't seem to work anything. i tried to reload, same.

3. i start to receive error message every minute at admin email.

[This message was automatically generated by REDCap]

Cron job "cronbigdata" failed for External Module "big_data_import" with the following Exception: Exception: Cannot create module instance, since the module with the following prefix is not enabled: big_data_import in E:\redcap\redcap_v9.1.2\ExternalModules\classes\ExternalModules.php:1699
Stack trace:
#0 E:\redcap\redcap_v9.1.2\ExternalModules\classes\ExternalModules.php(3330): ExternalModules\ExternalModules::getModuleInstance('big_data_import')
#1 E:\redcap\redcap_v9.1.2\Classes\Cron.php(295): ExternalModules\ExternalModules::callCronMethod('19', 'cronbigdata')
#2 E:\redcap\redcap_v9.1.2\cron.php(22): Cron->execute()
#3 E:\redcap\cron.php(11): include('E:\\redcap\\redca...')
#4 {main}

URL: http://
Server: redcap.xxx.edu (xxxRC1)
Module Name: (big_data_import)
Module Author(s): 
Run Time: 1 seconds

4. all my external modules are now disabled and i can't enable any of them. I tried to remove "big data import" and same.

5. here's the system log, the last two enable records showed i tried to re-enable the module and failed.
07/22/2019 2:58pm | xxx | Enable external module "big_data_import_v1.0" for system
-- | -- | --
07/22/2019 2:58pm | xxx | Enable external module "big_data_import_v1.0" for system
07/22/2019 2:56pm | xxx | File submitted via Big Data Import external module Import #1
07/22/2019 2:55pm | xxx | Modify configuration for external module "big_data_import_v1.0" for project
07/22/2019 2:54pm | xxx | Enable external module "big_data_import_v1.0" for project

6. and here's my project log:
07/22/2019 2:56pm | xxx | File submittedvia Big Data Import external module Import #1 | user = xxxFile = '1to20000.csvImport = 1Delimiter = ,Checked for existing records
-- | -- | -- | --
07/22/2019 2:55pm | xxx | Modify configuration for external module "big_data_import_v1.0" for project | import-email
07/22/2019 2:54pm | xxx | Enable external module "big_data_import_v1.0" for project

**Comment by knil-maloon** [comment]
@mmcev106 checked on this and it was an issue on the user's system.
