### ISSUE TITLE
Unable to import data when S3, Azure, or Webdav is used

### ISSUE THREAD

**Issue by mkarich** [vanderbilt-redcap/big-data-import#4]
We found that using the environment variable of EDOC.PATH references a blank file when non-local storage is used this preventing import.

I was able to fix this by changing lines 133 and 259 to $path = \Files::copyEdocToTemp($edoc);

This leverages the redcap function (Files\line 145) to copy the file to tmp and returns the path which can then be referenced for processing.

**Comment by knil-maloon** [comment]
Hi @mkarich as you mention for now the module only works on local environment. Thank you for your suggestion we will have in mind for future updates.
