### ISSUE TITLE
Import successful, but no records created

### ISSUE THREAD

**Issue by manuelsnyder** [vanderbilt-redcap/big-data-import#6]
Eva,

While creating a demo of your Big Data Import external module for our REDCap users, and I ran into an issue.

The import log said that my records were created successfully, and I received an email confirmation. However, no records were created in my project. I looked in the REDCap log, and it shows that the import was started, but no records were created, and no records appeared in the dashboard nor in the backend database.

I thought the issue might be the CSV or the way the project was built. It was a simple project with only a few text fields, so I didn't think that was the issue. I copied the project and set up the module again. And using the same CSV files, I was able to get the records imported into the project (consequently, I was able to demo the module without any problems).

I verified that the CSV files weren't the problem (because the imported records were created in the copied project), and the project wasn't the issue (since it worked using an exact copy of the failed project), I'm not sure what the issue could be.

I have attached screenshots of the "successful" import to see if you can help me figure out what the problem was. This way, I can help my users if it happens to them.

I also attached the CSV files and the data dictionary for the project so you can run it on your own system. However, you might not be able to reproduce this issue, since it might work like my copied project did. So, if you want, I can give you an account on our REDCap system and give you access to the project that's causing the issue. Just let me know.

I look forward to hearing from you.

Manuel Snyder, MSc 
The University of Arizona Health Sciences Center
Center for Biomedical Informatics and Biostatistics
Senior Programmer
TissueMetrix Administrator
REDCap Support

[big_data_import_demo.zip](https://github.com/vanderbilt-redcap/big-data-import/files/3876776/big_data_import_demo.zip)

**Comment by knil-maloon** [comment]
Hi @manuelsnyder without reproducing the error it will be hard to find a solution. I had someone in the comunity with the same issue as you described and what happened in their end is that the original project got corrupted and was unable to import

**Comment by manuelsnyder** [comment]
I thought that might be the case, since I deleted all of the data, then imported it again. However, when I copied the project, the import started working again. So, maybe the original project got corrupted during the data deletion. Not sure. Thanks for getting back to me.
