### ISSUE TITLE
Import fails: redcap_repeat_instrument must be the unique form name of a Repeating Instrument.

### ISSUE THREAD

**Issue by tertek** [vanderbilt-redcap/big-data-import#9]
We are experiencing an import issue with "Big Data Import" Module when trying to import a CSV with repeating fields.
The error message:

```
    {
     
        "errors": [
     
            "\"1020\",\"redcap_repeat_instrument\",\"address_information\",\"redcap_repeat_instrument must be the unique form name of a Repeating Instrument. It currently does not match the unique form name of any Repeating Instruments.                        Please fix this in the data import file and try again.\"",
     
            "\"1020\",\"redcap_repeat_instance\",\"1\",\"redcap_repeat_instance cannot have a value since this instrument or event is not a repeating instrument or repeating event, respectively.                        The redcap_repeat_instance field must be left blank for this row of data.\""
     
        ],
     
        "warnings": [],
     
        "ids": [],
     
        "item_count": 0
     
    }
```

Resetting via module configuration did not help. The CSV can be imported via "Data Import Tool" without errors. When removing the "1" from redcap_repeat_instance field as suggested in the error message we will have a successful import without data persistence, as described [here](https://community.projectredcap.org/questions/70164/data-is-not-importing-when-using-the-big-data-impo.html?childToView=131427#comment-131427).

REDCap 12.0.25 · PHP 7.3.33 (Linux/Unix OS) · MariaDB 10.3.32

**Comment by Fatimaalharthi** [comment]
Hello,
I am facing the same problem. 
Do you know how to solve it please?

**Comment by tertek** [comment]
Hello @Fatimaalharthi 
Unfortunately, we could not resolve the issue and are using the core Importer now.
Closing this, since no progress on the issue.

**Comment by Fatimaalharthi** [comment]
I found the solution to my problem

Thank you,
